---
- name: Reload __NAME__ quadlets
  ansible.builtin.command: systemctl --user -M __NAME__@ daemon-reload  # noqa: command-instead-of-module
  changed_when: true
  listen: __NAME__ quadlets changed

- name: Restart __NAME__ pod
  ansible.builtin.command: systemctl --user -M __NAME__@ restart __NAME__-pod.service  # noqa: command-instead-of-module
  changed_when: true
  listen: __NAME__ quadlets changed
