---
- name: Ensure the data directory exists
  ansible.builtin.file:
    path: "{{ service_home }}/data"
    state: directory
    owner: "{{ service_name }}"
    group: "{{ service_name }}"
    mode: '0755'

- name: Deploy the Quadlets
  ansible.builtin.import_role:
    name: quadlet_service
